[package]
name = "paymock_auth"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-cors = "0.7.1"
actix-web = "4.11.0"
actix-web-httpauth = "0.8.2"
chrono = "0.4.41"
chrono-tz = "0.10.4"
jsonwebtoken = "9.3.1"
serde = "1.0.219"
thiserror = "2.0.12"
