[package]
name = "paymock_auth"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-cors = "0.7.1"
actix-web = "4.11.0"
chrono = "0.4.41"
chrono-tz = "0.10.4"
hmac = "0.12.1"
jsonwebtoken = "9.3.1"
jwt = "0.16.0"
serde = "1.0.219"
sha2 = "0.10.9"
thiserror = "2.0.12"
