CREATE TABLE account.user (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid" UUID DEFAULT uuid_generate_v4() UNIQUE,
    "name" VARCHAR NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trigger_user_set_updated_at
BEFORE UPDATE ON account.user
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
